#pragma once

#include "global.h"

#include "magpoint.h"

#include "dclass/base/dabstractbase.h"
#include "dclass/base/dshapebase.h"
#include "dclass/base/dpolygonbase.h"
#include "dclass/base/dlinebase.h"

#include "dclass/text/dtextitem.h"

#include "dclass/basicshape/drectitem.h"
#include "dclass/basicshape/droundrectitem.h"
#include "dclass/basicshape/dellitem.h"
#include "dclass/base/../basicshape/dtriitem.h"
#include "dclass/basicshape/dparagramitem.h"
#include "dclass/basicshape/dtrapitem.h"

#include "dclass/flowshape/dfdocumentitem.h"
#include "dclass/basicshape/ddiaitem.h"
#include "dclass/flowshape/dfstartenditem.h"
#include "dclass/flowshape/dfpredefineitem.h"
#include "dclass/flowshape/dfmanualoperateitem.h"
#include "dclass/flowshape/dfmanualinputitem.h"
#include "dclass/flowshape/dfinternalstoreitem.h"
#include "dclass/flowshape/dfprepareitem.h"
#include "dclass/flowshape/dfprocessitem.h"
#include "dclass/flowshape/dfdelayitem.h"
#include "dclass/flowshape/dfoptionalprocessitem.h"
#include "dclass/flowshape/dfconditionitem.h"
#include "dclass/flowshape/dfdataitem.h"
#include "dclass/flowshape/dfnodeitem.h"
#include "dclass/flowshape/dforitem.h"
#include "dclass/flowshape/dfsummaryconnitem.h"
#include "dclass/flowshape/dfinformationitem.h"
#include "dclass/flowshape/dfcarditem.h"
#include "dmultidocitem.h"
#include "dclass/flowshape/dfmergeitem.h"
#include "dclass/flowshape/dfsortitem.h"
#include "dclass/flowshape/dfcompareitem.h"
#include "dclass/flowshape/dfoffpageitem.h"
#include "dclass/basicshape/dpentagonitem.h"
#include "dclass/flowshape/dfstoredataitem.h"
#include "ddirectstorageitem.h"
#include "ddiskitem.h"
#include "dorderstorageitem.h"
#include "dshowitem.h"

#include "dclass/line/dlineitem.h"
#include "dclass/line/dpolylineitem.h"
#include "dclass/line/dcurvelineitem.h"
